name : first workflow

on:
  woekflow_dispatch: 
   #push: 
     #branches: 
      #- main

jobs:
  job_1 :
   runs-on: ubuntu-latest

   steps: 
    - name: print welcome message
      run: echo "my first github action workflow"

    - name : Checkout
      uses: actions/checkout@v7.0.1

    - name : list repo files
      run: ls -la
  job_2 :
   runs-on: ubuntu-latest
   needs: job_1
   steps: 
    - name: print welcome message
      run: echo "my second github action workflow"

   


