on :
  workflow_dispatch:
   inputs:
     environment:
      description: "choses the environement"
      required: true
      default: "staging"
      type: choice
      options:
        - staging
        - production
      

jobs :
  deploy :
   runs-on: ubuntu-latest
   steps:
     - name: deploy-application
       run: echo "run the application on ${{inputs.environment}} environment!"
